### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by mitar** [aldeed/meteor-template-extension#11]
Please add tests. This is too critical code to be left without tests. It is using Meteor internals so it is unclear when they can change.

**Comment by zimme** [comment]
:+1:

**Comment by aldeed** [comment]
That's funny because I was thinking the same thing this morning. Will put it on the to-do list.

**Comment by grabbou** [comment]
@aldeed can do some basic scenarios + set up testing scheme based on your other projects ;)

**Comment by mitar** [comment]
In #12 I already prepared some tests so they have just to be extended.

**Comment by mitar** [comment]
Can you also enable Travis CI tests? I see that `.travis.yaml` is already there. I think it should just start working.

**Comment by aldeed** [comment]
Yep, just did and added readme badge

**Comment by aldeed** [comment]
After pulling @jgladch's tests, this is the list of things we still need tests for:

- [ ] copyAs
- [ ] replaces
- [ ] hooks
- [ ] onCreated
- [ ] onDestroyed
- [ ] onRendered

**Comment by jgladch** [comment]
On it
