### ISSUE TITLE
Support for anonymous Templates

### ISSUE THREAD

**Issue by mitar** [aldeed/meteor-template-extension#29]
Currently there is no way to really use methods without a name, ones you can get if you run `new Template(renderFunction).`

**Comment by aldeed** [comment]
Good idea.

**Comment by voidale** [comment]
@aldeed @mitar  Running `Template.Name.rendered()' for example will throw an error `Cannot read property 'name' of undefined` is this what you mean?  Any way to by pass this?

**Comment by mitar** [comment]
I think the whole codebase should be changed that it uses template objects internally. And only tries to resolve strings to template objects when it gets strings. Currently it is using strings everywhere.

**Comment by mitar** [comment]
Great job refactoring the code. While you are at it, I would suggest that it is also made so that all internal functions accept template objects, and then we just have one method which translates given template name argument to a template in public methods.

**Comment by aldeed** [comment]
@mitar I did. :) Did I miss something?

**Comment by mitar** [comment]
Hm, just that resolving is hard-coded in every function. But yea, it is only one line of code, maybe not needed.

BTW, there is also: https://github.com/meteor/meteor/blob/devel/packages/blaze/lookup.js#L105

**Comment by aldeed** [comment]
Added an issue for optimizing that eventually: https://github.com/aldeed/meteor-template-extension/issues/41
