### ISSUE TITLE
inheritsEventsFrom not working in current release

### ISSUE THREAD

**Issue by vazamb** [aldeed/meteor-template-extension#31]
I just updated Meteor to the newest 1.1.02 release and with the the template-extensions package to 3.4.3. It seems that the inheritsEventsFrom methods do not work anymore at all. No template is able to use the events from the templates they should inherit them from. I am not getting any errors it, it simply doesn't work anymore (i.e. buttons linked to an inherited event don't do anything when clicked)

Any known issues that might be causing this?

**Comment by projik** [comment]
I've only just started using this package in my Meteor project so I haven't seen the latest version break anything. However I have the same problem with **inheritsHelpersFrom**. None of the helper function are available in the templates that are supposed to inherit them. As vvazamb has mentioned there are no errors and nothing returned.

**Comment by SachaG** [comment]
I'm running into an issue with `inheritsHelpersFrom` as well, but I don't know if it's because it's broken or if it's something in my code. 

If I do `Template.foo.inheritsHelpersFrom("bar")`, then typing `Template.foo.__helpers` in the console shows the proper helpers. Yet when the template itself is rendered it doesn't seem to find any of the helpers.

**Comment by aldeed** [comment]
I'm hoping to do a review of this pkg in the next week or so, update tests and make sure the logic is working correctly with latest Meteor for some of the reported edge cases.

**Comment by mitar** [comment]
From my experience with Blaze Components and this package, I think the best would be also to move from having strings as main template identifiers, template objects themselves. And then we just resolve strings as needed, when we get them.

**Comment by hgrestebang** [comment]
I having the same problem: 
.
Template.cocinando.inheritsHelpersFrom('cocinando');
undefined //returned
Template.cookLarge.__helpers
Object {} //returned
get: (name)
has: (name)
set: (name, helper)
__proto__: Object

**Comment by hgrestebang** [comment]
Hi after some "hacking" I was able to simply copy the helpers like this:
Template['cookLarge'].__helpers = Template['cocinando'].__helpers;

I know the idea is using the extend function to make sure we inherited the helpers and don't overwrite. A good point to start is line 121

thisTemplate.__helpers = $.extend({}, thisTemplate.__helpers, otherTemplate.__helpers);

I see helpers are now Helpers MAP not an object.

**Comment by msolters** [comment]
Confirmed on v3.4.3, Meteor 1.2

Although the target template does show that its `__eventMaps` now include the other template's events, they are never fired.  There must be some kind of initialization that has to be done when a template is rendered, that actually applies the listeners corresponding to those event maps?  Perhaps merely overwriting `.__eventMaps` is not sufficient to actually implement the event listeners?

**Comment by msolters** [comment]
Oh my -- the fix is very simple, actually.  It's all about implementation.

`Template.targetTemplate.inheritsEventsFrom("sourceTemplate")` must be called **before** targetTemplate is rendered!!!

If you call that method after the `targetTemplate` has been rendered, the event map will be updated but it will not perform any actions.

**Comment by aldeed** [comment]
This has been rewritten to use the latest APIs in v4.0, so it should work better now.
