### ISSUE TITLE
Syntax to use temple.parent()?

### ISSUE THREAD

**Issue by davidystephenson** [aldeed/meteor-template-extension#32]
I can't seem to figure out how the template.parent() method is meant to be used. Running `template.parent()` in a template helper isn't working. A simple example would be very helpful.

**Comment by mitar** [comment]
In the template helper you first have to get the template instance. So whole call would be `Template.instance().parent()`.

**Comment by davidystephenson** [comment]
Thank you.

Sincerely,

David Y. Stephenson
davidystephenson.com
910.874.8740
