### ISSUE TITLE
Child Templates?

### ISSUE THREAD

**Issue by santiagopuentep** [aldeed/meteor-template-extension#34]
I was wandering if there is a way to access child templates. This extension and Blaze only talk about parent templates. Is there a reason for that?

Thanks!

**Comment by mitar** [comment]
What do you mean by "child template"? What does this mean to you?

Blaze Components do not operate around templates, but around components. You have both `componentParent` and `componentChildren` calls to traverse components up and down.

**Comment by santiagopuentep** [comment]
@mitar What I mean is to be able to access from the parent template to it's children templates, the ones that are inside the parent. To be able to search for example which is the last child template, etc.
Thanks for the tip about the components, I'll see if I use those, but do you know a way of doning this in simple blaze?

**Comment by mitar** [comment]
You could create that in `onCreated` of children templates, your children templates register themselves with the parent template.

**Comment by santiagopuentep** [comment]
Thanks Mitar. I'll add references of the children to the parent in the
onCreated callback.


---
Santiago Puente.

2015-05-28 17:57 GMT-03:00 Mitar <notifications@github.com>:

**Comment by mitar** [comment]
Or maybe in `onRendered`. Not exactly sure when `template.parent()` is available. But with this package you get `template.parent()`, which you can then use to store children into.

**Comment by santiagopuentep** [comment]
I was able to create something that works very well using onCreated to create the array to hold the children, onRendered to register to the parent and onDestroy to clear everything. To find the parent I use a while on the views to finde the first one with the name that starts with "Template."

All this done extending the prototype with registerChild, unregisterChild, getChildAt, etc.. I'll create a package and post it if I can create a more general, robust and tested solution because right now I have to call the init and destroy functions manually for every type of template.

Thanks for the help!

**Comment by mitar** [comment]
Yea. You just reimplemented part of Blaze Components. ;-)

**Comment by santiagopuentep** [comment]
lol, Oh, I'll check the blaze components when I have more time!

**Comment by santiagopuentep** [comment]
I'll have to learn coffeescript too..

**Comment by mitar** [comment]
So the next problem is exactly the one you are mentioning: how to make this feature reusable across multiple templates. This is when I gave up on templates and decides to make Blaze Components. :-)

**Comment by mitar** [comment]
You do not have to know CoffeeScript to use Blaze Components. Only if you would like to contribute to its development.

**Comment by santiagopuentep** [comment]
Thanks man, I think I'll use that library a lot.


---
Santiago Puente.

2015-05-28 20:25 GMT-03:00 Mitar <notifications@github.com>:

**Comment by santiagopuentep** [comment]
Do you know if there are any official plans to support this? Or where I
could post the request?


---
Santiago Puente.

2015-05-28 20:26 GMT-03:00 Santiago Puente <santiagopuentep@gmail.com>:

**Comment by mitar** [comment]
Support what? Request for what? For feature requests for Blaze, you should open them at Meteor repository.

**Comment by santiagopuentep** [comment]
For some kind of display hierarchy. I'll post this on the repo. Thanks
again!


---
Santiago Puente.

2015-05-28 20:28 GMT-03:00 Mitar <notifications@github.com>:
