### ISSUE TITLE
Getting firstNode with Template.forEach(callback)

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-template-extension#35]
I'm doing:

```
Template.onRendered(function () {
   console.log(this)
});
```

And: 

```
Template.forEach(function (template) {
   console.log(template)
});
```

In the first case, the template has a `firstNode` property which can be used to manipulate its DOM element, but in the second case that property doesn't exist. 

Is there a way to access it? Basically I'm trying to trigger a callback on all templates for arbitrary events (such as route changes), and not just once when they initially render. 

(see: https://www.youtube.com/watch?v=7Ux4wxg7Kko)

**Comment by aldeed** [comment]
Did you figure this out?

`Template.forEach` loops through the defined templates (`Blaze.Template` instances), while `onRendered` will be for a single template _instance_ (`Blaze.TemplateInstance` instance). I think you're asking to loop through all "currently rendered template instances".

So one way (untested) might be:

```js
Template.forEachCurrentlyRenderedInstance(function (templateInstance) {
   console.log(templateInstance)
});
```

Which you could create with:

```js
Template._renderedInstances = [];

Template.onRendered(function () {
  Template._renderedInstances.push(this);
});

Template.onDestroyed(function () {
  var i = Template._renderedInstances.indexOf(this);
  if (i > -1) {
    Template._renderedInstances.splice(i, 1);
  }
});

Template.forEachCurrentlyRenderedInstance = function (func) {
  Template._renderedInstances.forEach(func);
};
```

If it works, maybe we could add this to this package.

**Comment by aldeed** [comment]
Added `Template.forEachCurrentlyRenderedInstance` in 4.0
