### ISSUE TITLE
Regarding the template event overwrite 

### ISSUE THREAD

**Issue by boboci9** [aldeed/meteor-template-extension#38]
Hi,

Is there any possibility I can overwrite a template without the old template's events firing?

```
Template.openCartDrawer.events({
	'click #btn-checkout': function(event, template) {
		# new action
	},
	'click .remove-cart-item': function(event, template) {
		# new action
	}
})


Template.newOpenCartDrawer.inheritsHelpersFrom("openCartDrawer");
Template.newOpenCartDrawer.replaces("openCartDrawer");
```
With this setup the new events are firing but also the old ones which totally ruin the new functionality.
Any ideas how can I make only the new events firing? I tried defining the events using `Template.newOpenCartDrawer.events({` but then the new events are not firing.

Thanks for your help in advance.

**Comment by aldeed** [comment]
I released 4.0 with a new `Template.openCartDrawer.clearEventMaps()` you can call to remove those events. I've also clarified in the readme that `replaces` just replaces the render function.
