### ISSUE TITLE
copyAs could accept array

### ISSUE THREAD

**Issue by aldeed** [aldeed/meteor-template-extension#4]
From example in readme:

```js
Template.abstract_foo.copyAs('foo');
Template.abstract_foo.copyAs('bar');
```

If we wanted to simplify this slightly, especially in a case where you might have many more, `copyAs` could accept either array or string:

```js
Template.abstract_foo.copyAs(['foo', 'bar']);
```

**Comment by mitar** [comment]
BTW, what about @grabbou's idea that this should also work for other methods?

**Comment by jgladch** [comment]
@mitar, I'll handle that in subsequent feature branch once #14 is merged
