### ISSUE TITLE
replaces(templateName) not working

### ISSUE THREAD

**Issue by runlevelsix** [aldeed/meteor-template-extension#46]
I'm using Meteor 1.2.1 with template-extension v4.0.0 in a large-ish project and I can't seem to get the `replaces(templateName)` to work. 

I need to rearrange HTML in a template created by autoform so I can take advantage of an stylesheet that makes nicer-looking radio buttons (awesome-bootstrap-checkbox). So, I copied the `afRadioGroup` into a new, renamed template (`MyafRadioGroup`), in which I rearranged the HTML tags. I call `Template.MyafRadioGroup.replaces('afRadioGroup')` in JS, but when I inspect my rendered code, the new template has not replaced the old one.

I'm not sure what I'm doing wrong. I've pasted my code below.

``` html
<!-- client/components/MyafRadioGroup.html -->
<template name="MyafRadioGroup">
  <div class="af-radio-group" {{dsk}}>
  {{#each this.items}}
    <div class="radio">
      <input type="radio" value="{{this.value}}" {{atts}}>
      <label>
        {{this.label}}
      </label>
    </div>
  {{/each}}
  </div>
</template>

```

``` javascript
// client/components/MyafRadioGroup.js
Template.MyafRadioGroup.replaces("afRadioGroup");
```

**Comment by elGusto** [comment]
Probably you need to replace the template that is actually rendered. Autoform has "templates" (bootstrap, ionic, etc) so you need to replace the afRadioGroup_bootstrap template if you are using bootstrap.

**Comment by gregory** [comment]
+1 for @elGusto - @runlevelsix  you can use the meteor template inspector through the chrome extension to figure out what is the exact template that is being used.
