### ISSUE TITLE
How to get reactive var from parent template?

### ISSUE THREAD

**Issue by Shtirlits** [aldeed/meteor-template-extension#48]
In parent I have

```
Template.parent.onRendered(function() {
  this.reactiveVar = new ReactiveVar({});
  this.reactiveVar.set({
      positive: 1,
      negative: 2,
      neutral: 3
    })
});
```

```
Template.child.onRendered(function(){
    console.log(this.parent(1));
    console.log(this.parent(1).reactiveVar);
});
```

`console.log(template.parent(1));` shows me correct info, where I can see my `reactiveVar` object.
But for some reasons `console.log(this.parent(1).reactiveVar);` returns `undefined`.
`console.log(this.get('reactiveVar'));` returns `undefined` as well (`this.get('data')` works as expected).

Any suggestions on how can I get that value?

Thanks in advance.

UPD: everything I wrote above is true not only for `ReactiveVar`, but for var of every other type (object, string, etc.

**Comment by mitar** [comment]
You should assign variables in `onCreated`, not `onRendered`. Child `onRendered` is called before parent `onRendered`.

**Comment by Shtirlits** [comment]
@mitar but how does it happen that first `console.log(this.parent(1));` contains all the values I need?

**Comment by mitar** [comment]
`console.log` does not freeze logged objects. You log the reference to the object. Which is later on filled with `reactiveVar`. At the moment you are logging `reactiveVar` does not yet exist on the object, but when you inspect it later on, it does, because it was added.

**Comment by Shtirlits** [comment]
Thanks, closing the issue.
