### ISSUE TITLE
Confusing, why doesn't this work

### ISSUE THREAD

**Issue by reduxdj** [aldeed/meteor-template-extension#49]
I am working on a branch of meteor admin, thad does it's magic to render the templates and icons, my use case is all I want to do is populate a span above my input. I'm completely baffled why the following doesn't work autoamagically.

character:
    autoform:
      type: 'afFieldIcon'
    type: String
    optional: true

<template name="afFieldIcon">
  <span id="icon-span"  style="font-family:icons;font-size:2em;">{{{convertUnicode}}}</span>
   {{> Template.dynamic template=getTemplateName data=innerContext}}
</template>

How would I extend the AfFieldInput and add my own custom template wrapper, so i can add events and so forth?

**Comment by aldeed** [comment]
Closing issue backlog
