### ISSUE TITLE
copyAs does not override events?

### ISSUE THREAD

**Issue by SimonVuong** [aldeed/meteor-template-extension#52]
while copyAs does override helpers, it does not override events. is there a way to do this?

**Comment by aldeed** [comment]
copyAs makes a new template that copies all helpers, events, and hooks from the source template. After you copy, any helpers, events, or hooks you add will go onto the copy only. It's not clear what this issue is without a reproduction, so I'm closing this

**Comment by aldeed** [comment]
Actually, I think this might be referring to the fact that the event map is an array, so if you call `events` with the same key as already defined in the copied template, it will add another event for that rather than overwriting the first. I will clarify in the docs
