### ISSUE TITLE
templateInstance.set() is not a function

### ISSUE THREAD

**Issue by MohammedEssehemy** [aldeed/meteor-template-extension#56]
I read in the README: 
use template.set(propName, value) to set the value of the first property named propName on the current or an ancestor template instance.

but when trying to run the following code, 
```javascript
      Template.instance().set('someProp', 'someVal');
```
I get the following error 
 ```javascript
        TypeError: Template.instance(...).set is not a function
```
although the getter function is working well: 
```javascript
    Template.instance().get('someProp');
```

**Comment by aldeed** [comment]
@MohammedEssehemy I'm not sure if you ever figured this out, but set was added in 4.1.0 I believe, so check in .meteor/versions to make sure you have that version installed. If another package you are using relies on an earlier version, that might have prevented Meteor from pulling in the latest package.
