### ISSUE TITLE
Added fields conflicts with mongoDB

### ISSUE THREAD

**Issue by LaChips** [aldeed/meteor-template-extension#58]
Hi,

My mongo is throwing error because of the "$length" field added by template-extension but I can't really remove it as I need it.
Is it possible, using an option, to replace that $ sign with an other one, like _ ?

Thanks !

**Comment by aldeed** [comment]
@LaChips Why do you think template-extension adds `$length`? I think that's just a handlebars thing. (Post example code if you disagree.)

**Comment by LaChips** [comment]
Ho, yeah, sorry, I’m going to close this issue, I just miss read the package’s name. It comes from another one.

Sorry for that mistake.
