### ISSUE TITLE
Inheriting template hooks

### ISSUE THREAD

**Issue by rhyslbw** [aldeed/meteor-template-extension#7]
What are your thoughts on being able to inherit the abstract template's hooks as an option param in the copyAs method?

For example, say there's an abstract template manager with similar features to this pattern https://www.discovermeteor.com/blog/template-level-subscriptions/, but there are multiple implementations needing separate template views. There are probably other ways to work with just the single template, but given there is already the concept of inheritance here, it might fit.

Good to hear your thoughts before I investigate further.

**Comment by aldeed** [comment]
Hmm. I wonder why we're not copying hooks by default. @grabbou?

Probably all (hooks, events, helpers) should be copied by default but with options to not copy them.

**Comment by rhyslbw** [comment]
Yes It does make more sense to inherit all from the parent by default. I guessed there was a good reason not to considering their absence…

**Comment by grabbou** [comment]
Well, I can't really tell you guys WHY though :D Going to modify that tomorrow.

**Comment by rhyslbw** [comment]
Awesome, thanks @grabbou

**Comment by rhyslbw** [comment]
Did you make any progress on this bug @grabbou? If I get the chance I will write some tests for this particular feature and submit a PR

**Comment by jgladch** [comment]
Changes are up and waiting in #14, extended to allow for arrays in #16, tested in #17

**Comment by rhyslbw** [comment]
:+1:
